---
- name: Install Crowdsec package
  apt:
    name: crowdsec
    state: present
    update_cache: yes

- name: Remove Crowdsec iptables bouncer package if installed
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: absent
  register: bouncer_remove_result
  ignore_errors: yes

- name: Install Crowdsec iptables bouncer package
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present
  register: bouncer_install_result

- name: Generate Crowdsec LAPI key
  command: sudo cscli bouncers add iptables-bouncer
  register: lapi_key_output

- name: Configure Crowdsec
  template:
    src: crowdsec.yaml.j2
    dest: /etc/crowdsec/config.yaml
  notify:
    - Restart Crowdsec service

- name: Configure Crowdsec iptables bouncer
  template:
    src: crowdsec-firewall-bouncer-iptables.yaml.j2
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer-iptables.yaml
  notify:
    - Restart Crowdsec iptables bouncer service

- name: Start and enable Crowdsec service
  systemd:
    name: crowdsec
    state: started
    enabled: yes

- name: Start and enable Crowdsec iptables bouncer service
  systemd:
    name: crowdsec-firewall-bouncer
    state: started
    enabled: yes
