---
- name: Add Crowdsec repository
  apt_repository:
    repo: deb {{ crowdsec_repo_url }}/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main
    state: present

- name: Install Crowdsec package
  apt:
    name: crowdsec
    state: present
    update_cache: yes
  when: crowdsec_agent_version == "latest"

- name: Install specific Crowdsec version
  apt:
    name: crowdsec={{ crowdsec_agent_version }}
    state: present
  when: crowdsec_agent_version != "latest"

- name: Configure Crowdsec
  template:
    src: crowdsec.yaml.j2
    dest: /etc/crowdsec/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Crowdsec

- name: Configure Crowdsec firewall bouncer
  template:
    src: crowdsec-firewall-bouncer.yaml.j2
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Crowdsec

- name: Start and enable Crowdsec service
  service:
    name: crowdsec
    state: started
    enabled: yes
