
    - name: set cron MAILTO
      become: true
      cronvar:
        user: root
        name: MAILTO
        value: "{{ mail_to }}"

    - name: add crontab to run clamav daily at 3 AM
      become: true
      cron:
        name: clamav daily run
        minute: "0"
        hour: "3"
        job: "/usr/bin/clamscan -ri --exclude-dir=\"^/sys\" --no-summary /"
        user: root
