    - name: Requirements-Playbook
      hosts: debian-server
      remote_user: root
      vars_files: ./group_vars/variables.yml
      gather_facts: yes
      connection: ssh
      vars:
        ansible_ssh_private_key_file: "{{ ssh_location }}"
      roles:
        - requirements
