    - name: Main-Playbook
      hosts: debian-server
      remote_user: "{{ user_name }}"
      gather_facts: yes
      vars_files: ./group_vars/variables.yml
      gather_facts: yes # You may not need this if you have fact gathering disabled in your ansible.cfg
      connection: ssh # Change to 'paramiko' if you face any issues
      vars:
        ansible_ssh_private_key_file: "{{ ssh_location }}"
      roles:
        - packages
        - ssh
        - password-quality
        - unattended-upgrades
        - firewall
        # mail
        - clamav
        - rkhunter
        - auditd
        - lynis
        #- crowdsec
