control:
  hosts:
    45.145.166.162

workers:
  hosts:
    #node01:
    #  ansible_connection: ssh
    #node02:
    #  ansible_connection: ssh

cube:
  children:
    control:
    workers:

debian-server:
  hosts:
    45.145.166.162
