---
- name: Restart Crowdsec service
  systemd:
    name: crowdsec
    state: restarted

- name: Restart Crowdsec iptables bouncer service
  systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
