    - name: enforce strong passwords with pam_pwquality
      become: true
      lineinfile:
        dest: /etc/pam.d/common-password
        regexp: '^.*pam_pwquality.so.*$'
        line: 'password        requisite                       pam_pwquality.so retry=3 minlen=10 difok=3 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1 maxrepeat=3 gecoschec'
